# Generated by Django 4.2 on 2025-03-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_teamuser_first_name_remove_teamuser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamuser',
            name='location',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
    ]
