# Generated by Django 4.2 on 2025-03-25 21:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teamuser_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.IntegerField(default=0)),
                ('away_goals', models.IntegerField(default=0)),
                ('match_date', models.DateTimeField(default=datetime.datetime(2025, 3, 26, 21, 52, 16, 373940))),
                ('venue', models.CharField(default='Stadium', max_length=100)),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to=settings.AUTH_USER_MODEL)),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_date'],
            },
        ),
    ]
